piqe-test-libraries/piqe-ocp-lib

- piqe_ocp_lib/api/resources/ocp_base.py
- piqe_ocp_lib/api/resources/ocp_secrets.py
- piqe_ocp_lib/tests/resources/test_ocp_base.py
- piqe_ocp_lib/tests/resources/test_ocp_operators.py
All changes introduced in the downstream repository since migrating upstream are captured in this PR.
> Resync - Apply changes from the downstream repository.

- piqe_ocp_lib/tests/resources/test_ocp_operators.py
Skip the failing test methods to until the issues can be resolved.
> Testing - Skip failing test methods.

- README.md
> badr-feature - Fixed directory name in README file.

- piqe_ocp_lib/api/resources/__init__.py
- piqe_ocp_lib/api/resources/ocp_base.py
- piqe_ocp_lib/api/resources/ocp_cluster_operators.py
- piqe_ocp_lib/api/resources/ocp_cluster_versions.py
- piqe_ocp_lib/api/resources/ocp_configs.py
- piqe_ocp_lib/api/resources/ocp_control_planes.py
- piqe_ocp_lib/api/resources/ocp_deploymentconfigs.py
- piqe_ocp_lib/api/resources/ocp_health_checker.py
- piqe_ocp_lib/api/resources/ocp_routes.py
- piqe_ocp_lib/api/resources/ocp_secrets.py
- piqe_ocp_lib/tests/resources/test_ocp_base.py
- piqe_ocp_lib/tests/resources/test_ocp_cluster_operators.py
- piqe_ocp_lib/tests/resources/test_ocp_cluster_versions.py
- piqe_ocp_lib/tests/resources/test_ocp_configs.py
- piqe_ocp_lib/tests/resources/test_ocp_control_planes.py
- piqe_ocp_lib/tests/resources/test_ocp_health_checker.py
- piqe_ocp_lib/tests/resources/test_ocp_nodes.py
- piqe_ocp_lib/tests/resources/test_ocp_secrets.py
[CSS-2630] Write unittests for OCP Health Checks
> [CSS-2629] Write libs for Openshift Health Checks

- Jenkinsfile
Post processing has been added to archive artifacts.
> MPQEENABLE-390 - Jenkinsfile needs post processing

- piqe_ocp_lib/api/resources/ocp_health_checker.py
- piqe_ocp_lib/tests/resources/test_ocp_health_checker.py
> CSS-2984 Return NodeReadyStatus for nodes when all_nodes_healthy = False

- piqe_ocp_lib/api/resources/ocp_operators.py
- piqe_ocp_lib/api/tasks/operator_ops.py
- piqe_ocp_lib/tests/resources/test_ocp_operators.py
CatalogSourceConfig is no longer supported as of OCP4.5. Removing from the operator test libs.
> MPQEENABLE-427 Deprecate CatalogSourceConfig resource support 

- piqe_ocp_lib/api/resources/ocp_apps.py
- piqe_ocp_lib/api/resources/ocp_base.py
- piqe_ocp_lib/api/resources/ocp_events.py
- piqe_ocp_lib/api/resources/ocp_nodes.py
- piqe_ocp_lib/api/resources/ocp_operators.py
- piqe_ocp_lib/api/resources/ocp_pods.py
- piqe_ocp_lib/api/resources/ocp_projects.py
- piqe_ocp_lib/api/resources/ocp_service_accounts.py
- piqe_ocp_lib/api/resources/ocp_templates.py
- piqe_ocp_lib/tests/resources/test_ocp_base.py
- piqe_ocp_lib/tests/resources/test_ocp_operators.py
Note : Since other classes inherit ocp_base, So make changes accordingly in all relevant classes.
> [MPQEENABLE-306] Refactor ocp_base to make dynamic_client and k8s_client singleton.

- piqe_ocp_lib/api/tasks/populate_cluster/config_schemas.py
- piqe_ocp_lib/api/tasks/populate_cluster/populate_cluster.py
- piqe_ocp_lib/tests/config/smoke_ocp_config.yaml
- piqe_ocp_lib/tests/resources/test_ocp_node_metrics.py
- piqe_ocp_lib/tests/tasks/test_populate_ocp.py
Request to add populate_cluster module and its associated files and test.
> [CSS-3282] Added populate ocp script with associated files and test.

- piqe_ocp_lib/api/resources/__init__.py
- piqe_ocp_lib/api/resources/ocp_limit_ranges.py
- piqe_ocp_lib/tests/resources/test_ocp_limit_ranges.py
* Added the LimitRange resource API and accompanying unit tests
> [CSS-3399] Add Resource API for LimitRange object

- piqe_ocp_lib/api/resources/ocp_base.py
- piqe_ocp_lib/api/resources/ocp_operators.py
- piqe_ocp_lib/api/resources/ocp_projects.py
- piqe_ocp_lib/api/tasks/operator_ops.py
- piqe_ocp_lib/tests/helpers.py
- piqe_ocp_lib/tests/resources/test_ocp_base.py
- piqe_ocp_lib/tests/resources/test_ocp_operators.py
- poetry.lock
- pyproject.toml
* Removed `OperatorSource` from OperatorInstaller task - API removed >= 4.6
* Remove `CatalogSource` from OperatorInstaller task - API removed >= 4.5
* Remove _source_processor method of OperatorInstaller's task
* Refactor to use f-strings
* Also solves [CSSWA-356]
> [CSSWA-451] Openshift 4.6 removed features

- piqe_ocp_lib/api/resources/ocp_operators.py
- piqe_ocp_lib/api/tasks/operator_ops.py
- piqe_ocp_lib/tests/resources/test_ocp_operators.py
- piqe_ocp_lib/tests/tasks/test_populate_ocp.py
- Add operator_uninstall in task
> [CSSWA-303] Operator uninstallation

- piqe_ocp_lib/api/resources/__init__.py
- piqe_ocp_lib/api/resources/ocp_base.py
- piqe_ocp_lib/api/resources/ocp_virtual_machine.py
- piqe_ocp_lib/tests/resources/test_ocp_virtual_machine.py
Add support for VirtualMachine resource
- Add VM's subresources client
- VM client
- VM abstraction
> [CSSWA-475] VirtualMachine resources/abstractions

- piqe_ocp_lib/api/resources/ocp_nodes.py
- piqe_ocp_lib/tests/resources/test_ocp_nodes.py
Add libraries to mark masters/workers schedulable/unschedulable
and unit tests to validate the same
> MPS-31 & MPS-32 Mark master/worker schedulable/unschedulable

- .github/workflows/build.yml
- Makefile
- README.md
- piqe_ocp_lib/api/resources/ocp_base.py
- piqe_ocp_lib/api/resources/ocp_machine_management.py
- piqe_ocp_lib/api/resources/ocp_nodes.py
- piqe_ocp_lib/api/tasks/populate_cluster/populate_cluster.py
- piqe_ocp_lib/tests/resources/test_ocp_nodes.py
* This should resolve the pulls #58 and #48
* I've also updated the README to include info from
downstream repos so that it's located with the repo
rather than in a separate location
> Fix docs and github linting actions

- piqe_ocp_lib/api/resources/ocp_cluster_versions.py
- piqe_ocp_lib/api/resources/ocp_health_checker.py
Fix function upgrade_cluster_version & check_cluster_version_operator_health so that ocp upgrade could be performed.
> Fix func upgrade_cluster_version & check_cluster_version_operator_health

- piqe_ocp_lib/api/resources/ocp_nodes.py
- piqe_ocp_lib/tests/resources/test_ocp_nodes.py
Add func to get available cpu & mem resources from schedulable nodes in ocp cluster
> Add func to get available resources on ocp cluster

- piqe_ocp_lib/api/tasks/operator_ops.py
- piqe_ocp_lib/tests/config/smoke_ocp_config.yaml
- pyproject.toml
Only run resources test for pre check-in
> CSSWA-544 Only run resources tests for pre check-in

- piqe_ocp_lib/api/resources/__init__.py
- piqe_ocp_lib/api/resources/ocp_machine_management.py
- piqe_ocp_lib/tests/resources/test_ocp_machine_management.py
Created MachineHealthCheck api -> ocp_machine_management.py
Added Tests to TestOcpMachineHealthCheck ->
- test_get_all_machine_health_checks (list)
- test_get_machine_health_check (by name)
- test_machine_health_check_is_configured
Signed-off-by: bbhavsar <bbhavsar@redhat.com>
> MPS-36 Verify no MachineHealthChecks are configured

- piqe_ocp_lib/api/constants.py
- piqe_ocp_lib/api/ocp_exception_handler.py
- piqe_ocp_lib/api/ocp_exceptions.py
- piqe_ocp_lib/api/resources/ocp_projects.py
- piqe_ocp_lib/tests/resources/test_ocp_projects.py
- poetry.lock
This PR brings improvement to raising exceptions & their handling, for the ocp projects module for now.
I have added some new custom exceptions & removed unused ones.
Also fix for issue where exceptions & logger ERRORs are reported while watching a project/namespace, even though may not be expected/actual error.
Some topics to consider:
1. I have made function `handle_namespace_exception` local to ocp_projects. Does it makes more sense to add to a global utils/exception utils, for use by other modules?
2. Any enhancements or suggestions for better naming.
3. Any improvements to other modules' exceptions which are bothersome & can be better handled
> Improve exception handling for ocp projects
